/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as JogoIdRouteImport } from './routes/jogo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoIdRoute = JogoIdRouteImport.update({
  id: '/jogo/$id',
  path: '/jogo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/jogos': typeof JogosRoute
  '/perfil': typeof PerfilRoute
  '/jogo/$id': typeof JogoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/jogos': typeof JogosRoute
  '/perfil': typeof PerfilRoute
  '/jogo/$id': typeof JogoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/jogos': typeof JogosRoute
  '/perfil': typeof PerfilRoute
  '/jogo/$id': typeof JogoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar'
    | '/entrar'
    | '/explorar'
    | '/jogos'
    | '/perfil'
    | '/jogo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar'
    | '/entrar'
    | '/explorar'
    | '/jogos'
    | '/perfil'
    | '/jogo/$id'
  id:
    | '__root__'
    | '/'
    | '/criar'
    | '/entrar'
    | '/explorar'
    | '/jogos'
    | '/perfil'
    | '/jogo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarRoute: typeof CriarRoute
  EntrarRoute: typeof EntrarRoute
  ExplorarRoute: typeof ExplorarRoute
  JogosRoute: typeof JogosRoute
  PerfilRoute: typeof PerfilRoute
  JogoIdRoute: typeof JogoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo/$id': {
      id: '/jogo/$id'
      path: '/jogo/$id'
      fullPath: '/jogo/$id'
      preLoaderRoute: typeof JogoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarRoute: CriarRoute,
  EntrarRoute: EntrarRoute,
  ExplorarRoute: ExplorarRoute,
  JogosRoute: JogosRoute,
  PerfilRoute: PerfilRoute,
  JogoIdRoute: JogoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
